CREATE TABLE `generation_half_hourly` (
  `time` datetime NOT NULL,
  `embedded_wind` decimal(4,2) UNSIGNED NOT NULL,
  `embedded_solar` decimal(4,2) UNSIGNED NOT NULL,
  `pumped_storage_pumping` decimal(4,2) NOT NULL,
  `coal` decimal(4,2) UNSIGNED NOT NULL,
  `ccgt` decimal(4,2) UNSIGNED NOT NULL,
  `ocgt` decimal(4,2) UNSIGNED NOT NULL,
  `nuclear` decimal(4,2) UNSIGNED NOT NULL,
  `oil` decimal(4,2) UNSIGNED NOT NULL,
  `wind` decimal(4,2) UNSIGNED NOT NULL,
  `hydro` decimal(4,2) UNSIGNED NOT NULL,
  `pumped` decimal(4,2) UNSIGNED NOT NULL,
  `biomass` decimal(4,2) UNSIGNED NOT NULL,
  `other` decimal(4,2) UNSIGNED NOT NULL,
  `ifa` decimal(3,2) NOT NULL,
  `moyle` decimal(3,2) NOT NULL,
  `britned` decimal(3,2) NOT NULL,
  `ewic` decimal(3,2) NOT NULL,
  `nemo` decimal(3,2) NOT NULL,
  `ifa2` decimal(3,2) NOT NULL,
  `nsl` decimal(3,2) NOT NULL,
  `eleclink` decimal(3,2) NOT NULL,
  PRIMARY KEY (`time`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;